### ISSUE TITLE
Incorrect Url Path Generation with Redoc .NET Core 3

### ISSUE THREAD

**Issue by Kuroiyatsu** [domaindrivendev/Swashbuckle.AspNetCore#1395]
When using Swashbuckle -> Redoc, the generated Url paths for the end-points are incorrect. This problem was not an issue before updating my project from .Net Core 2.2 to 3.0 (which required Swashbuckle updates).

Application Version: .NET Core 3.0
Swashbuckle.AspNetCore: v5.0.0-rc4
Swashbuckle.AspNetCore.Filters: v5.0.0-rc8
Swashbuckle.AspNetCore.ReDoc: v5.0.0-rc4

Startup.cs has the following: 

` 
services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("Scheduler", new OpenApiInfo
                {
                    Title = "Scheduler",
                    Version = "1.0.0",
                    Description = "Handles scheduling."
                });
`

and 
`
  app.UseSwagger();
            app.UseReDoc(opt =>
            {
                opt.RoutePrefix = "docs";
                opt.SpecUrl = "../swagger/Scheduler/swagger.json";
                opt.DocumentTitle = "Scheduler API";
            });
`

Everything seems to work fine, but the generated Url paths now keep adding "swagger" to the front, which is an invalid end-point.

So what was once "https://mywebsite/someendpoint" has become "https://mywebsite/**swagger**/someendpoint".

Attempting to remove the the leading "swagger" in SpecUrl property just causes the doc generation to fail entirely.

Ultimately, the error shows up on the UI, but it seems to be related to the generation on the back-end. 

Thanks

**Comment by aochagavia-infi** [comment]
FWIW I am experiencing a similar problem, using the same versions of the libraries

**Comment by aochagavia-infi** [comment]
Update: I downloaded the `swagger.json` to check the API specification and was surprised to find out that nowhere you see an explicit `swagger` string. This leads me to think that the bug cannot be in the doc generation part. It looks more like ReDoc somehow thinks the base path is the same as the path where the spec is.

**Comment by Kuroiyatsu** [comment]
@aochagavia-infi 

What's interesting, I deployed the same project to our Dev servers, and the issue isn't there. Running locally, I see it. I should be able to deploy it up to the test server in the next couple of days and we'll see. It isn't AS big for us if it only happens locally I suppose.

I'll update with what I see when things go to the Test server.

**Comment by Kuroiyatsu** [comment]
@aochagavia-infi so it is still an issue locally, but I do not get the issue on my Test server. Only when debugging locally, if that provides some further clue as to what exactly is happening.

**Comment by aochagavia-infi** [comment]
Interesting... I do see the issue on my test server

**Comment by ngbrown** [comment]
This isn't specific to .NET Core 3.  I'm using .NET Core 2.1 and see the same with `Swashbuckle.AspNetCore.ReDoc` version `5.0.0-rc4`.

In my startup.cs:

```cs
app.UseSwagger(opt => { opt.RouteTemplate = "api-docs/{documentName}/docs.json"; });

app.UseReDoc(opt => {
    opt.RoutePrefix = "api-docs";
    opt.SpecUrl = "v1/docs.json";
});
```

And in the sidebar next to each operation, the `/api-docs/v1/` path is prefixed:

![Screenshot - 2019-12-03_07-49-59](https://user-images.githubusercontent.com/228987/70061685-f3a7cd80-15a1-11ea-8e01-e45a902ee0be.png)

**Comment by domaindrivendev** [comment]
@Kuroiyatsu are still seeing this with the latest version (`5.6.3` at time of writing)? If not, please close. If so, please create a minimal app (i.e. start from empty proj) that repro's the issue and post to github so I can pull down and troubleshoot.

**Comment by domaindrivendev** [comment]
Closing due to inactivity
